version: "3.9"

services:
  django:
    image: street_politics-django:latest
    container_name: django_app
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker1:
    image: street_politics-django:latest
    command: celery -A street_politics worker --loglevel=info --concurrency=2 --hostname=worker1@%h --logfile=/var/log/celery/worker1.log
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - celery_logs:/var/log/celery
    deploy:
      replicas: 1
      
  celery_worker2:
    image: street_politics-django:latest
    command: celery -A street_politics worker --loglevel=info --concurrency=2 --hostname=worker2@%h --logfile=/var/log/celery/worker2.log
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - celery_logs:/var/log/celery
    deploy:
      replicas: 1


